/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author FABRIZIO
 */
public class DigCerrarVenta extends javax.swing.JDialog {

    private int idProyecto;
    private double costoMateriales;
    public DigCerrarVenta(java.awt.Frame parent, boolean modal, int id, double costo) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Guardamos los datos recibidos
        this.idProyecto = id;
        this.costoMateriales = costo;
        
        // Mostramos el costo (Fijo)
        txtCostoMat.setText(String.valueOf(costoMateriales));
        
        // Calculamos la primera sugerencia
        calcular();
    }
    // --- CEREBRO MATEMÁTICO ---
    private void calcular() {
        try {
            // 1. Leemos los valores (si están vacíos usamos 0)
            double porcentaje = 0;
            if(!txtPorcentaje.getText().isEmpty()) 
                porcentaje = Double.parseDouble(txtPorcentaje.getText());
            
            double gastos = 0;
            if(!txtGastos.getText().isEmpty()) 
                gastos = Double.parseDouble(txtGastos.getText());
            
            // 2. Calculamos la sugerencia
            // Regla del espejo: Costo * (Porcentaje/100)
            double ganancia = costoMateriales * (porcentaje / 100.0);
            double sugerido = costoMateriales + ganancia + gastos;
            
            // 3. Ponemos el precio sugerido (SOLO si el usuario no ha escrito uno propio a mano)
            // Truco: Para no complicarnos, actualizamos siempre el sugerido por ahora
            txtPrecioFinal.setText(String.format("%.2f", sugerido).replace(",", "."));
            
            // 4. Calculamos Saldo
            double precioFinal = Double.parseDouble(txtPrecioFinal.getText());
            double adelanto = 0;
            if(!txtAdelanto.getText().isEmpty()) 
                adelanto = Double.parseDouble(txtAdelanto.getText());
                
            double saldo = precioFinal - adelanto;
            txtSaldo.setText(String.format("%.2f", saldo).replace(",", "."));
            
        } catch (Exception e) {
            // Si escribe letras en vez de números, no hacemos nada
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCostoMat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGastos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioFinal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAdelanto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CIERRE DE VENTA");
        setModal(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cierre de Venta");

        jLabel2.setText("Costo de Materiales");

        txtCostoMat.setEditable(false);
        txtCostoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoMatActionPerformed(evt);
            }
        });

        jLabel4.setText("% Mano de Obra");

        jLabel6.setText("Gastos Adiccionales");

        jLabel7.setText("PRECIO FINAL");

        jLabel8.setText("Adelanto");

        jLabel9.setText("Saldo Pendiente");

        btnConfirmar.setText("CONFIRMA VENTA");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCostoMat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGastos))
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAdelanto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSaldo))
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCostoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtAdelanto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoMatActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
        // 1. RECOLECTAR DATOS (Puede que tu papá los haya editado a mano)
        // Usamos replace(",", ".") por si pone comas decimales
        double porcentaje = Double.parseDouble(txtPorcentaje.getText().replace(",", "."));
        double precioFinal = Double.parseDouble(txtPrecioFinal.getText().replace(",", "."));
        
        // Si la caja de adelanto está vacía, es 0
        double adelanto = 0.0;
        if (!txtAdelanto.getText().isEmpty()) {
            adelanto = Double.parseDouble(txtAdelanto.getText().replace(",", "."));
        }
        
        // El saldo lo recalculamos por seguridad
        double saldo = precioFinal - adelanto;
        
        // 2. LLAMAR AL DAO PARA ACTUALIZAR EN LA BASE DE DATOS
        DAO.ProyectoDAO dao = new DAO.ProyectoDAO();
        
        // Usamos la variable 'idProyecto' que guardamos al inicio (en el constructor)
        boolean exito = dao.cerrarVenta(this.idProyecto, porcentaje, precioFinal, adelanto, saldo);
        
        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "✨ ¡VENTA REGISTRADA CON ÉXITO! ✨\nYa puedes cobrar.");
            this.dispose(); // Cierra la ventana final
            try {
            UTIL.GeneradorPDF pdf = new UTIL.GeneradorPDF();
            pdf.generarCotizacion(this.idProyecto);
        } catch (Exception e) {
            System.out.println("Error invocando PDF: " + e);
        }
        // ---------------------------------------------

        // Línea 234 que ya tienes:
        this.dispose();
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "⚠️ Ocurrió un error al actualizar los datos.");
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, verifica que los montos sean números válidos.");
    }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdelanto;
    private javax.swing.JTextField txtCostoMat;
    private javax.swing.JTextField txtGastos;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtPrecioFinal;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
