/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmHistorialProyectos extends javax.swing.JFrame {

    /**
     * Creates new form FrmHistorialProyectos
     */
    public FrmHistorialProyectos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Historial de Cotizaciones - EBANIX");
        cargarTabla(); // <--- IMPORTANTE: Cargamos los datos al abrir
    }
    private void cargarTabla() {
        DAO.ProyectoDAO dao = new DAO.ProyectoDAO();
        DefaultTableModel modelo = dao.listarHistorial();
        tblHistorial.setModel(modelo);
        
        // Ajuste visual (Opcional): Ancho de columnas
        tblHistorial.getColumnModel().getColumn(0).setPreferredWidth(30); // ID pequeño
        tblHistorial.getColumnModel().getColumn(1).setPreferredWidth(150); // Cliente grande
        tblHistorial.getColumnModel().getColumn(2).setPreferredWidth(200); // Proyecto grande
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHistorial);

        jButton1.setText("VER PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton1)
                        .addGap(192, 192, 192)
                        .addComponent(jButton2)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila = tblHistorial.getSelectedRow();
        
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "⚠️ Primero selecciona un proyecto de la lista.");
            return;
        }

        // 2. Obtener el ID del proyecto seleccionado (Está en la columna 0)
        int idProyecto = Integer.parseInt(tblHistorial.getValueAt(fila, 0).toString());

        // 3. Generar el PDF de nuevo (Reutilizamos tu clase mágica)
        JOptionPane.showMessageDialog(this, "Generando copia del PDF...");
        
        try {
            UTIL.GeneradorPDF pdf = new UTIL.GeneradorPDF();
            pdf.generarCotizacion(idProyecto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Verificar si seleccionó una fila
    int fila = tblHistorial.getSelectedRow();

    if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "¡Selecciona un proyecto primero!");
    return;
}

// 2. Preguntar "¿Estás seguro?" (Para no borrar por error)
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Seguro que quieres borrar este proyecto?", 
        "Cuidado", 
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
    
    // 3. Capturar el ID (Asumo que está en la Columna 0, la primera)
    int id = Integer.parseInt(tblHistorial.getValueAt(fila, 0).toString());
    
    // 4. LLAMAR A TU CÓDIGO EXISTENTE
    DAO.ProyectoDAO dao = new DAO.ProyectoDAO();
    
    if (dao.eliminarProyecto(id)) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Proyecto eliminado!");
        
        // 5. ACTUALIZAR LA TABLA (Pon aquí el nombre de tu método de carga)
        // Ejemplo: listarProyectos(); o cargarTabla();
        cargarTabla(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar.");
    }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorialProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
